/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppPublicLayoutRouteImport } from './pages/_app/_public/layout'
import { Route as AppAdminLayoutRouteImport } from './pages/_app/_admin/layout'
import { Route as AuthSignUpIndexRouteImport } from './pages/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './pages/_auth/sign-in/index'
import { Route as AppPublicIndexRouteImport } from './pages/_app/_public/index'
import { Route as AppRelatedBlogLayoutRouteImport } from './pages/_app/_related/blog/layout'
import { Route as AppRelatedComplianceLayoutRouteImport } from './pages/_app/_related/_compliance/layout'
import { Route as AppRelatedBlogIndexRouteImport } from './pages/_app/_related/blog/index'
import { Route as AppPublicRewardsIndexRouteImport } from './pages/_app/_public/rewards/index'
import { Route as AppAdminDashboardIndexRouteImport } from './pages/_app/_admin/dashboard/index'
import { Route as AuthSignUpChar126componentsSignUpFormRouteImport } from './pages/_auth/sign-up/~components/sign-up-form'
import { Route as AuthSignInChar126componentsSignInFormRouteImport } from './pages/_auth/sign-in/~components/sign-in-form'
import { Route as AppRelatedComplianceTermsOfUseRouteImport } from './pages/_app/_related/_compliance/terms-of-use'
import { Route as AppRelatedComplianceProhibitedProductsRouteImport } from './pages/_app/_related/_compliance/prohibited-products'
import { Route as AppRelatedCompliancePrivacyPolicyRouteImport } from './pages/_app/_related/_compliance/privacy-policy'
import { Route as AppRelatedComplianceContactRouteImport } from './pages/_app/_related/_compliance/contact'
import { Route as AppRelatedComplianceComplaintsRouteImport } from './pages/_app/_related/_compliance/complaints'
import { Route as AppRelatedBlogChar126componentsNavbarRouteImport } from './pages/_app/_related/blog/~components/navbar'
import { Route as AppRelatedBlogChar126componentsBlogArticlesRouteImport } from './pages/_app/_related/blog/~components/blog-articles'
import { Route as AppPublicChar126componentsSectionsTaxesRouteImport } from './pages/_app/_public/~components/sections/taxes'
import { Route as AppPublicChar126componentsSectionsRewardsRouteImport } from './pages/_app/_public/~components/sections/rewards'
import { Route as AppPublicChar126componentsSectionsResourcesRouteImport } from './pages/_app/_public/~components/sections/resources'
import { Route as AppPublicChar126componentsSectionsRecentArticlesRouteImport } from './pages/_app/_public/~components/sections/recent-articles'
import { Route as AppPublicChar126componentsSectionsIntroRouteImport } from './pages/_app/_public/~components/sections/intro'
import { Route as AppPublicChar126componentsSectionsCompaniesMarqueeRouteImport } from './pages/_app/_public/~components/sections/companies-marquee'
import { Route as AppPublicChar126componentsSectionsBenefitsRouteImport } from './pages/_app/_public/~components/sections/benefits'
import { Route as AppRelatedBlogArticleContentArticleIdIndexRouteImport } from './pages/_app/_related/blog/_article-content/$articleId/index'
import { Route as AppRelatedBlogChar126componentsContentArticlesFiltersRouteImport } from './pages/_app/_related/blog/~components/content/articles-filters'
import { Route as AppRelatedBlogChar126componentsContentArticleCardRouteImport } from './pages/_app/_related/blog/~components/content/article-card'
import { Route as AppPublicRewardsChar126componentsSectionsRewardsListRouteImport } from './pages/_app/_public/rewards/~components/sections/rewards-list'
import { Route as AppPublicRewardsChar126componentsSectionsPicturesCarouselRouteImport } from './pages/_app/_public/rewards/~components/sections/pictures-carousel'
import { Route as AppPublicRewardsChar126componentsSectionsIntroRouteImport } from './pages/_app/_public/rewards/~components/sections/intro'
import { Route as AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRouteImport } from './pages/_app/_related/blog/_article-content/$articleId/~components/article-with-error'
import { Route as AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRouteImport } from './pages/_app/_related/blog/_article-content/$articleId/~components/article-skeleton'
import { Route as AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRouteImport } from './pages/_app/_related/blog/_article-content/$articleId/~components/article-sharing'
import { Route as AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRouteImport } from './pages/_app/_related/blog/_article-content/$articleId/~components/article-not-found'
import { Route as AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRouteImport } from './pages/_app/_related/blog/_article-content/$articleId/~components/dynamic-zone/related-articles'
import { Route as AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRouteImport } from './pages/_app/_related/blog/_article-content/$articleId/~components/dynamic-zone/related-article-card'
import { Route as AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRouteImport } from './pages/_app/_related/blog/_article-content/$articleId/~components/content-renderer/rich-content-renderer'

const AppPublicLayoutRoute = AppPublicLayoutRouteImport.update({
  id: '/_app/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminLayoutRoute = AppAdminLayoutRouteImport.update({
  id: '/_app/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/_auth/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/_auth/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPublicIndexRoute = AppPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPublicLayoutRoute,
} as any)
const AppRelatedBlogLayoutRoute = AppRelatedBlogLayoutRouteImport.update({
  id: '/_app/_related/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatedComplianceLayoutRoute =
  AppRelatedComplianceLayoutRouteImport.update({
    id: '/_app/_related/_compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRelatedBlogIndexRoute = AppRelatedBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRelatedBlogLayoutRoute,
} as any)
const AppPublicRewardsIndexRoute = AppPublicRewardsIndexRouteImport.update({
  id: '/rewards/',
  path: '/rewards/',
  getParentRoute: () => AppPublicLayoutRoute,
} as any)
const AppAdminDashboardIndexRoute = AppAdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppAdminLayoutRoute,
} as any)
const AuthSignUpChar126componentsSignUpFormRoute =
  AuthSignUpChar126componentsSignUpFormRouteImport.update({
    id: '/_auth/sign-up/~components/sign-up-form',
    path: '/sign-up/~components/sign-up-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSignInChar126componentsSignInFormRoute =
  AuthSignInChar126componentsSignInFormRouteImport.update({
    id: '/_auth/sign-in/~components/sign-in-form',
    path: '/sign-in/~components/sign-in-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRelatedComplianceTermsOfUseRoute =
  AppRelatedComplianceTermsOfUseRouteImport.update({
    id: '/terms-of-use',
    path: '/terms-of-use',
    getParentRoute: () => AppRelatedComplianceLayoutRoute,
  } as any)
const AppRelatedComplianceProhibitedProductsRoute =
  AppRelatedComplianceProhibitedProductsRouteImport.update({
    id: '/prohibited-products',
    path: '/prohibited-products',
    getParentRoute: () => AppRelatedComplianceLayoutRoute,
  } as any)
const AppRelatedCompliancePrivacyPolicyRoute =
  AppRelatedCompliancePrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => AppRelatedComplianceLayoutRoute,
  } as any)
const AppRelatedComplianceContactRoute =
  AppRelatedComplianceContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AppRelatedComplianceLayoutRoute,
  } as any)
const AppRelatedComplianceComplaintsRoute =
  AppRelatedComplianceComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => AppRelatedComplianceLayoutRoute,
  } as any)
const AppRelatedBlogChar126componentsNavbarRoute =
  AppRelatedBlogChar126componentsNavbarRouteImport.update({
    id: '/~components/navbar',
    path: '/~components/navbar',
    getParentRoute: () => AppRelatedBlogLayoutRoute,
  } as any)
const AppRelatedBlogChar126componentsBlogArticlesRoute =
  AppRelatedBlogChar126componentsBlogArticlesRouteImport.update({
    id: '/~components/blog-articles',
    path: '/~components/blog-articles',
    getParentRoute: () => AppRelatedBlogLayoutRoute,
  } as any)
const AppPublicChar126componentsSectionsTaxesRoute =
  AppPublicChar126componentsSectionsTaxesRouteImport.update({
    id: '/~components/sections/taxes',
    path: '/~components/sections/taxes',
    getParentRoute: () => AppPublicLayoutRoute,
  } as any)
const AppPublicChar126componentsSectionsRewardsRoute =
  AppPublicChar126componentsSectionsRewardsRouteImport.update({
    id: '/~components/sections/rewards',
    path: '/~components/sections/rewards',
    getParentRoute: () => AppPublicLayoutRoute,
  } as any)
const AppPublicChar126componentsSectionsResourcesRoute =
  AppPublicChar126componentsSectionsResourcesRouteImport.update({
    id: '/~components/sections/resources',
    path: '/~components/sections/resources',
    getParentRoute: () => AppPublicLayoutRoute,
  } as any)
const AppPublicChar126componentsSectionsRecentArticlesRoute =
  AppPublicChar126componentsSectionsRecentArticlesRouteImport.update({
    id: '/~components/sections/recent-articles',
    path: '/~components/sections/recent-articles',
    getParentRoute: () => AppPublicLayoutRoute,
  } as any)
const AppPublicChar126componentsSectionsIntroRoute =
  AppPublicChar126componentsSectionsIntroRouteImport.update({
    id: '/~components/sections/intro',
    path: '/~components/sections/intro',
    getParentRoute: () => AppPublicLayoutRoute,
  } as any)
const AppPublicChar126componentsSectionsCompaniesMarqueeRoute =
  AppPublicChar126componentsSectionsCompaniesMarqueeRouteImport.update({
    id: '/~components/sections/companies-marquee',
    path: '/~components/sections/companies-marquee',
    getParentRoute: () => AppPublicLayoutRoute,
  } as any)
const AppPublicChar126componentsSectionsBenefitsRoute =
  AppPublicChar126componentsSectionsBenefitsRouteImport.update({
    id: '/~components/sections/benefits',
    path: '/~components/sections/benefits',
    getParentRoute: () => AppPublicLayoutRoute,
  } as any)
const AppRelatedBlogArticleContentArticleIdIndexRoute =
  AppRelatedBlogArticleContentArticleIdIndexRouteImport.update({
    id: '/_article-content/$articleId/',
    path: '/$articleId/',
    getParentRoute: () => AppRelatedBlogLayoutRoute,
  } as any)
const AppRelatedBlogChar126componentsContentArticlesFiltersRoute =
  AppRelatedBlogChar126componentsContentArticlesFiltersRouteImport.update({
    id: '/~components/content/articles-filters',
    path: '/~components/content/articles-filters',
    getParentRoute: () => AppRelatedBlogLayoutRoute,
  } as any)
const AppRelatedBlogChar126componentsContentArticleCardRoute =
  AppRelatedBlogChar126componentsContentArticleCardRouteImport.update({
    id: '/~components/content/article-card',
    path: '/~components/content/article-card',
    getParentRoute: () => AppRelatedBlogLayoutRoute,
  } as any)
const AppPublicRewardsChar126componentsSectionsRewardsListRoute =
  AppPublicRewardsChar126componentsSectionsRewardsListRouteImport.update({
    id: '/rewards/~components/sections/rewards-list',
    path: '/rewards/~components/sections/rewards-list',
    getParentRoute: () => AppPublicLayoutRoute,
  } as any)
const AppPublicRewardsChar126componentsSectionsPicturesCarouselRoute =
  AppPublicRewardsChar126componentsSectionsPicturesCarouselRouteImport.update({
    id: '/rewards/~components/sections/pictures-carousel',
    path: '/rewards/~components/sections/pictures-carousel',
    getParentRoute: () => AppPublicLayoutRoute,
  } as any)
const AppPublicRewardsChar126componentsSectionsIntroRoute =
  AppPublicRewardsChar126componentsSectionsIntroRouteImport.update({
    id: '/rewards/~components/sections/intro',
    path: '/rewards/~components/sections/intro',
    getParentRoute: () => AppPublicLayoutRoute,
  } as any)
const AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRoute =
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRouteImport.update(
    {
      id: '/_article-content/$articleId/~components/article-with-error',
      path: '/$articleId/~components/article-with-error',
      getParentRoute: () => AppRelatedBlogLayoutRoute,
    } as any,
  )
const AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRoute =
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRouteImport.update(
    {
      id: '/_article-content/$articleId/~components/article-skeleton',
      path: '/$articleId/~components/article-skeleton',
      getParentRoute: () => AppRelatedBlogLayoutRoute,
    } as any,
  )
const AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRoute =
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRouteImport.update(
    {
      id: '/_article-content/$articleId/~components/article-sharing',
      path: '/$articleId/~components/article-sharing',
      getParentRoute: () => AppRelatedBlogLayoutRoute,
    } as any,
  )
const AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRoute =
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRouteImport.update(
    {
      id: '/_article-content/$articleId/~components/article-not-found',
      path: '/$articleId/~components/article-not-found',
      getParentRoute: () => AppRelatedBlogLayoutRoute,
    } as any,
  )
const AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRoute =
  AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRouteImport.update(
    {
      id: '/_article-content/$articleId/~components/dynamic-zone/related-articles',
      path: '/$articleId/~components/dynamic-zone/related-articles',
      getParentRoute: () => AppRelatedBlogLayoutRoute,
    } as any,
  )
const AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRoute =
  AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRouteImport.update(
    {
      id: '/_article-content/$articleId/~components/dynamic-zone/related-article-card',
      path: '/$articleId/~components/dynamic-zone/related-article-card',
      getParentRoute: () => AppRelatedBlogLayoutRoute,
    } as any,
  )
const AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRoute =
  AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRouteImport.update(
    {
      id: '/_article-content/$articleId/~components/content-renderer/rich-content-renderer',
      path: '/$articleId/~components/content-renderer/rich-content-renderer',
      getParentRoute: () => AppRelatedBlogLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/blog': typeof AppRelatedBlogLayoutRouteWithChildren
  '/': typeof AppPublicIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/complaints': typeof AppRelatedComplianceComplaintsRoute
  '/contact': typeof AppRelatedComplianceContactRoute
  '/privacy-policy': typeof AppRelatedCompliancePrivacyPolicyRoute
  '/prohibited-products': typeof AppRelatedComplianceProhibitedProductsRoute
  '/terms-of-use': typeof AppRelatedComplianceTermsOfUseRoute
  '/sign-in/~components/sign-in-form': typeof AuthSignInChar126componentsSignInFormRoute
  '/sign-up/~components/sign-up-form': typeof AuthSignUpChar126componentsSignUpFormRoute
  '/dashboard': typeof AppAdminDashboardIndexRoute
  '/rewards': typeof AppPublicRewardsIndexRoute
  '/blog/': typeof AppRelatedBlogIndexRoute
  '/~components/sections/benefits': typeof AppPublicChar126componentsSectionsBenefitsRoute
  '/~components/sections/companies-marquee': typeof AppPublicChar126componentsSectionsCompaniesMarqueeRoute
  '/~components/sections/intro': typeof AppPublicChar126componentsSectionsIntroRoute
  '/~components/sections/recent-articles': typeof AppPublicChar126componentsSectionsRecentArticlesRoute
  '/~components/sections/resources': typeof AppPublicChar126componentsSectionsResourcesRoute
  '/~components/sections/rewards': typeof AppPublicChar126componentsSectionsRewardsRoute
  '/~components/sections/taxes': typeof AppPublicChar126componentsSectionsTaxesRoute
  '/blog/~components/blog-articles': typeof AppRelatedBlogChar126componentsBlogArticlesRoute
  '/blog/~components/navbar': typeof AppRelatedBlogChar126componentsNavbarRoute
  '/rewards/~components/sections/intro': typeof AppPublicRewardsChar126componentsSectionsIntroRoute
  '/rewards/~components/sections/pictures-carousel': typeof AppPublicRewardsChar126componentsSectionsPicturesCarouselRoute
  '/rewards/~components/sections/rewards-list': typeof AppPublicRewardsChar126componentsSectionsRewardsListRoute
  '/blog/~components/content/article-card': typeof AppRelatedBlogChar126componentsContentArticleCardRoute
  '/blog/~components/content/articles-filters': typeof AppRelatedBlogChar126componentsContentArticlesFiltersRoute
  '/blog/$articleId': typeof AppRelatedBlogArticleContentArticleIdIndexRoute
  '/blog/$articleId/~components/article-not-found': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRoute
  '/blog/$articleId/~components/article-sharing': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRoute
  '/blog/$articleId/~components/article-skeleton': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRoute
  '/blog/$articleId/~components/article-with-error': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRoute
  '/blog/$articleId/~components/content-renderer/rich-content-renderer': typeof AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRoute
  '/blog/$articleId/~components/dynamic-zone/related-article-card': typeof AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRoute
  '/blog/$articleId/~components/dynamic-zone/related-articles': typeof AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof AppPublicIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/complaints': typeof AppRelatedComplianceComplaintsRoute
  '/contact': typeof AppRelatedComplianceContactRoute
  '/privacy-policy': typeof AppRelatedCompliancePrivacyPolicyRoute
  '/prohibited-products': typeof AppRelatedComplianceProhibitedProductsRoute
  '/terms-of-use': typeof AppRelatedComplianceTermsOfUseRoute
  '/sign-in/~components/sign-in-form': typeof AuthSignInChar126componentsSignInFormRoute
  '/sign-up/~components/sign-up-form': typeof AuthSignUpChar126componentsSignUpFormRoute
  '/dashboard': typeof AppAdminDashboardIndexRoute
  '/rewards': typeof AppPublicRewardsIndexRoute
  '/blog': typeof AppRelatedBlogIndexRoute
  '/~components/sections/benefits': typeof AppPublicChar126componentsSectionsBenefitsRoute
  '/~components/sections/companies-marquee': typeof AppPublicChar126componentsSectionsCompaniesMarqueeRoute
  '/~components/sections/intro': typeof AppPublicChar126componentsSectionsIntroRoute
  '/~components/sections/recent-articles': typeof AppPublicChar126componentsSectionsRecentArticlesRoute
  '/~components/sections/resources': typeof AppPublicChar126componentsSectionsResourcesRoute
  '/~components/sections/rewards': typeof AppPublicChar126componentsSectionsRewardsRoute
  '/~components/sections/taxes': typeof AppPublicChar126componentsSectionsTaxesRoute
  '/blog/~components/blog-articles': typeof AppRelatedBlogChar126componentsBlogArticlesRoute
  '/blog/~components/navbar': typeof AppRelatedBlogChar126componentsNavbarRoute
  '/rewards/~components/sections/intro': typeof AppPublicRewardsChar126componentsSectionsIntroRoute
  '/rewards/~components/sections/pictures-carousel': typeof AppPublicRewardsChar126componentsSectionsPicturesCarouselRoute
  '/rewards/~components/sections/rewards-list': typeof AppPublicRewardsChar126componentsSectionsRewardsListRoute
  '/blog/~components/content/article-card': typeof AppRelatedBlogChar126componentsContentArticleCardRoute
  '/blog/~components/content/articles-filters': typeof AppRelatedBlogChar126componentsContentArticlesFiltersRoute
  '/blog/$articleId': typeof AppRelatedBlogArticleContentArticleIdIndexRoute
  '/blog/$articleId/~components/article-not-found': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRoute
  '/blog/$articleId/~components/article-sharing': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRoute
  '/blog/$articleId/~components/article-skeleton': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRoute
  '/blog/$articleId/~components/article-with-error': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRoute
  '/blog/$articleId/~components/content-renderer/rich-content-renderer': typeof AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRoute
  '/blog/$articleId/~components/dynamic-zone/related-article-card': typeof AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRoute
  '/blog/$articleId/~components/dynamic-zone/related-articles': typeof AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/_admin': typeof AppAdminLayoutRouteWithChildren
  '/_app/_public': typeof AppPublicLayoutRouteWithChildren
  '/_app/_related/_compliance': typeof AppRelatedComplianceLayoutRouteWithChildren
  '/_app/_related/blog': typeof AppRelatedBlogLayoutRouteWithChildren
  '/_app/_public/': typeof AppPublicIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_app/_related/_compliance/complaints': typeof AppRelatedComplianceComplaintsRoute
  '/_app/_related/_compliance/contact': typeof AppRelatedComplianceContactRoute
  '/_app/_related/_compliance/privacy-policy': typeof AppRelatedCompliancePrivacyPolicyRoute
  '/_app/_related/_compliance/prohibited-products': typeof AppRelatedComplianceProhibitedProductsRoute
  '/_app/_related/_compliance/terms-of-use': typeof AppRelatedComplianceTermsOfUseRoute
  '/_auth/sign-in/~components/sign-in-form': typeof AuthSignInChar126componentsSignInFormRoute
  '/_auth/sign-up/~components/sign-up-form': typeof AuthSignUpChar126componentsSignUpFormRoute
  '/_app/_admin/dashboard/': typeof AppAdminDashboardIndexRoute
  '/_app/_public/rewards/': typeof AppPublicRewardsIndexRoute
  '/_app/_related/blog/': typeof AppRelatedBlogIndexRoute
  '/_app/_public/~components/sections/benefits': typeof AppPublicChar126componentsSectionsBenefitsRoute
  '/_app/_public/~components/sections/companies-marquee': typeof AppPublicChar126componentsSectionsCompaniesMarqueeRoute
  '/_app/_public/~components/sections/intro': typeof AppPublicChar126componentsSectionsIntroRoute
  '/_app/_public/~components/sections/recent-articles': typeof AppPublicChar126componentsSectionsRecentArticlesRoute
  '/_app/_public/~components/sections/resources': typeof AppPublicChar126componentsSectionsResourcesRoute
  '/_app/_public/~components/sections/rewards': typeof AppPublicChar126componentsSectionsRewardsRoute
  '/_app/_public/~components/sections/taxes': typeof AppPublicChar126componentsSectionsTaxesRoute
  '/_app/_related/blog/~components/blog-articles': typeof AppRelatedBlogChar126componentsBlogArticlesRoute
  '/_app/_related/blog/~components/navbar': typeof AppRelatedBlogChar126componentsNavbarRoute
  '/_app/_public/rewards/~components/sections/intro': typeof AppPublicRewardsChar126componentsSectionsIntroRoute
  '/_app/_public/rewards/~components/sections/pictures-carousel': typeof AppPublicRewardsChar126componentsSectionsPicturesCarouselRoute
  '/_app/_public/rewards/~components/sections/rewards-list': typeof AppPublicRewardsChar126componentsSectionsRewardsListRoute
  '/_app/_related/blog/~components/content/article-card': typeof AppRelatedBlogChar126componentsContentArticleCardRoute
  '/_app/_related/blog/~components/content/articles-filters': typeof AppRelatedBlogChar126componentsContentArticlesFiltersRoute
  '/_app/_related/blog/_article-content/$articleId/': typeof AppRelatedBlogArticleContentArticleIdIndexRoute
  '/_app/_related/blog/_article-content/$articleId/~components/article-not-found': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRoute
  '/_app/_related/blog/_article-content/$articleId/~components/article-sharing': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRoute
  '/_app/_related/blog/_article-content/$articleId/~components/article-skeleton': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRoute
  '/_app/_related/blog/_article-content/$articleId/~components/article-with-error': typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRoute
  '/_app/_related/blog/_article-content/$articleId/~components/content-renderer/rich-content-renderer': typeof AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRoute
  '/_app/_related/blog/_article-content/$articleId/~components/dynamic-zone/related-article-card': typeof AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRoute
  '/_app/_related/blog/_article-content/$articleId/~components/dynamic-zone/related-articles': typeof AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/blog'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/complaints'
    | '/contact'
    | '/privacy-policy'
    | '/prohibited-products'
    | '/terms-of-use'
    | '/sign-in/~components/sign-in-form'
    | '/sign-up/~components/sign-up-form'
    | '/dashboard'
    | '/rewards'
    | '/blog/'
    | '/~components/sections/benefits'
    | '/~components/sections/companies-marquee'
    | '/~components/sections/intro'
    | '/~components/sections/recent-articles'
    | '/~components/sections/resources'
    | '/~components/sections/rewards'
    | '/~components/sections/taxes'
    | '/blog/~components/blog-articles'
    | '/blog/~components/navbar'
    | '/rewards/~components/sections/intro'
    | '/rewards/~components/sections/pictures-carousel'
    | '/rewards/~components/sections/rewards-list'
    | '/blog/~components/content/article-card'
    | '/blog/~components/content/articles-filters'
    | '/blog/$articleId'
    | '/blog/$articleId/~components/article-not-found'
    | '/blog/$articleId/~components/article-sharing'
    | '/blog/$articleId/~components/article-skeleton'
    | '/blog/$articleId/~components/article-with-error'
    | '/blog/$articleId/~components/content-renderer/rich-content-renderer'
    | '/blog/$articleId/~components/dynamic-zone/related-article-card'
    | '/blog/$articleId/~components/dynamic-zone/related-articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/complaints'
    | '/contact'
    | '/privacy-policy'
    | '/prohibited-products'
    | '/terms-of-use'
    | '/sign-in/~components/sign-in-form'
    | '/sign-up/~components/sign-up-form'
    | '/dashboard'
    | '/rewards'
    | '/blog'
    | '/~components/sections/benefits'
    | '/~components/sections/companies-marquee'
    | '/~components/sections/intro'
    | '/~components/sections/recent-articles'
    | '/~components/sections/resources'
    | '/~components/sections/rewards'
    | '/~components/sections/taxes'
    | '/blog/~components/blog-articles'
    | '/blog/~components/navbar'
    | '/rewards/~components/sections/intro'
    | '/rewards/~components/sections/pictures-carousel'
    | '/rewards/~components/sections/rewards-list'
    | '/blog/~components/content/article-card'
    | '/blog/~components/content/articles-filters'
    | '/blog/$articleId'
    | '/blog/$articleId/~components/article-not-found'
    | '/blog/$articleId/~components/article-sharing'
    | '/blog/$articleId/~components/article-skeleton'
    | '/blog/$articleId/~components/article-with-error'
    | '/blog/$articleId/~components/content-renderer/rich-content-renderer'
    | '/blog/$articleId/~components/dynamic-zone/related-article-card'
    | '/blog/$articleId/~components/dynamic-zone/related-articles'
  id:
    | '__root__'
    | '/_app/_admin'
    | '/_app/_public'
    | '/_app/_related/_compliance'
    | '/_app/_related/blog'
    | '/_app/_public/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_app/_related/_compliance/complaints'
    | '/_app/_related/_compliance/contact'
    | '/_app/_related/_compliance/privacy-policy'
    | '/_app/_related/_compliance/prohibited-products'
    | '/_app/_related/_compliance/terms-of-use'
    | '/_auth/sign-in/~components/sign-in-form'
    | '/_auth/sign-up/~components/sign-up-form'
    | '/_app/_admin/dashboard/'
    | '/_app/_public/rewards/'
    | '/_app/_related/blog/'
    | '/_app/_public/~components/sections/benefits'
    | '/_app/_public/~components/sections/companies-marquee'
    | '/_app/_public/~components/sections/intro'
    | '/_app/_public/~components/sections/recent-articles'
    | '/_app/_public/~components/sections/resources'
    | '/_app/_public/~components/sections/rewards'
    | '/_app/_public/~components/sections/taxes'
    | '/_app/_related/blog/~components/blog-articles'
    | '/_app/_related/blog/~components/navbar'
    | '/_app/_public/rewards/~components/sections/intro'
    | '/_app/_public/rewards/~components/sections/pictures-carousel'
    | '/_app/_public/rewards/~components/sections/rewards-list'
    | '/_app/_related/blog/~components/content/article-card'
    | '/_app/_related/blog/~components/content/articles-filters'
    | '/_app/_related/blog/_article-content/$articleId/'
    | '/_app/_related/blog/_article-content/$articleId/~components/article-not-found'
    | '/_app/_related/blog/_article-content/$articleId/~components/article-sharing'
    | '/_app/_related/blog/_article-content/$articleId/~components/article-skeleton'
    | '/_app/_related/blog/_article-content/$articleId/~components/article-with-error'
    | '/_app/_related/blog/_article-content/$articleId/~components/content-renderer/rich-content-renderer'
    | '/_app/_related/blog/_article-content/$articleId/~components/dynamic-zone/related-article-card'
    | '/_app/_related/blog/_article-content/$articleId/~components/dynamic-zone/related-articles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppAdminLayoutRoute: typeof AppAdminLayoutRouteWithChildren
  AppPublicLayoutRoute: typeof AppPublicLayoutRouteWithChildren
  AppRelatedComplianceLayoutRoute: typeof AppRelatedComplianceLayoutRouteWithChildren
  AppRelatedBlogLayoutRoute: typeof AppRelatedBlogLayoutRouteWithChildren
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
  AuthSignInChar126componentsSignInFormRoute: typeof AuthSignInChar126componentsSignInFormRoute
  AuthSignUpChar126componentsSignUpFormRoute: typeof AuthSignUpChar126componentsSignUpFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/_public': {
      id: '/_app/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppPublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_public/': {
      id: '/_app/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppPublicIndexRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_related/blog': {
      id: '/_app/_related/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AppRelatedBlogLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_related/_compliance': {
      id: '/_app/_related/_compliance'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRelatedComplianceLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_related/blog/': {
      id: '/_app/_related/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof AppRelatedBlogIndexRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_public/rewards/': {
      id: '/_app/_public/rewards/'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppPublicRewardsIndexRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_admin/dashboard/': {
      id: '/_app/_admin/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAdminDashboardIndexRouteImport
      parentRoute: typeof AppAdminLayoutRoute
    }
    '/_auth/sign-up/~components/sign-up-form': {
      id: '/_auth/sign-up/~components/sign-up-form'
      path: '/sign-up/~components/sign-up-form'
      fullPath: '/sign-up/~components/sign-up-form'
      preLoaderRoute: typeof AuthSignUpChar126componentsSignUpFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in/~components/sign-in-form': {
      id: '/_auth/sign-in/~components/sign-in-form'
      path: '/sign-in/~components/sign-in-form'
      fullPath: '/sign-in/~components/sign-in-form'
      preLoaderRoute: typeof AuthSignInChar126componentsSignInFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_related/_compliance/terms-of-use': {
      id: '/_app/_related/_compliance/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof AppRelatedComplianceTermsOfUseRouteImport
      parentRoute: typeof AppRelatedComplianceLayoutRoute
    }
    '/_app/_related/_compliance/prohibited-products': {
      id: '/_app/_related/_compliance/prohibited-products'
      path: '/prohibited-products'
      fullPath: '/prohibited-products'
      preLoaderRoute: typeof AppRelatedComplianceProhibitedProductsRouteImport
      parentRoute: typeof AppRelatedComplianceLayoutRoute
    }
    '/_app/_related/_compliance/privacy-policy': {
      id: '/_app/_related/_compliance/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof AppRelatedCompliancePrivacyPolicyRouteImport
      parentRoute: typeof AppRelatedComplianceLayoutRoute
    }
    '/_app/_related/_compliance/contact': {
      id: '/_app/_related/_compliance/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppRelatedComplianceContactRouteImport
      parentRoute: typeof AppRelatedComplianceLayoutRoute
    }
    '/_app/_related/_compliance/complaints': {
      id: '/_app/_related/_compliance/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AppRelatedComplianceComplaintsRouteImport
      parentRoute: typeof AppRelatedComplianceLayoutRoute
    }
    '/_app/_related/blog/~components/navbar': {
      id: '/_app/_related/blog/~components/navbar'
      path: '/~components/navbar'
      fullPath: '/blog/~components/navbar'
      preLoaderRoute: typeof AppRelatedBlogChar126componentsNavbarRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_related/blog/~components/blog-articles': {
      id: '/_app/_related/blog/~components/blog-articles'
      path: '/~components/blog-articles'
      fullPath: '/blog/~components/blog-articles'
      preLoaderRoute: typeof AppRelatedBlogChar126componentsBlogArticlesRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_public/~components/sections/taxes': {
      id: '/_app/_public/~components/sections/taxes'
      path: '/~components/sections/taxes'
      fullPath: '/~components/sections/taxes'
      preLoaderRoute: typeof AppPublicChar126componentsSectionsTaxesRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_public/~components/sections/rewards': {
      id: '/_app/_public/~components/sections/rewards'
      path: '/~components/sections/rewards'
      fullPath: '/~components/sections/rewards'
      preLoaderRoute: typeof AppPublicChar126componentsSectionsRewardsRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_public/~components/sections/resources': {
      id: '/_app/_public/~components/sections/resources'
      path: '/~components/sections/resources'
      fullPath: '/~components/sections/resources'
      preLoaderRoute: typeof AppPublicChar126componentsSectionsResourcesRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_public/~components/sections/recent-articles': {
      id: '/_app/_public/~components/sections/recent-articles'
      path: '/~components/sections/recent-articles'
      fullPath: '/~components/sections/recent-articles'
      preLoaderRoute: typeof AppPublicChar126componentsSectionsRecentArticlesRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_public/~components/sections/intro': {
      id: '/_app/_public/~components/sections/intro'
      path: '/~components/sections/intro'
      fullPath: '/~components/sections/intro'
      preLoaderRoute: typeof AppPublicChar126componentsSectionsIntroRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_public/~components/sections/companies-marquee': {
      id: '/_app/_public/~components/sections/companies-marquee'
      path: '/~components/sections/companies-marquee'
      fullPath: '/~components/sections/companies-marquee'
      preLoaderRoute: typeof AppPublicChar126componentsSectionsCompaniesMarqueeRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_public/~components/sections/benefits': {
      id: '/_app/_public/~components/sections/benefits'
      path: '/~components/sections/benefits'
      fullPath: '/~components/sections/benefits'
      preLoaderRoute: typeof AppPublicChar126componentsSectionsBenefitsRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_related/blog/_article-content/$articleId/': {
      id: '/_app/_related/blog/_article-content/$articleId/'
      path: '/$articleId'
      fullPath: '/blog/$articleId'
      preLoaderRoute: typeof AppRelatedBlogArticleContentArticleIdIndexRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_related/blog/~components/content/articles-filters': {
      id: '/_app/_related/blog/~components/content/articles-filters'
      path: '/~components/content/articles-filters'
      fullPath: '/blog/~components/content/articles-filters'
      preLoaderRoute: typeof AppRelatedBlogChar126componentsContentArticlesFiltersRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_related/blog/~components/content/article-card': {
      id: '/_app/_related/blog/~components/content/article-card'
      path: '/~components/content/article-card'
      fullPath: '/blog/~components/content/article-card'
      preLoaderRoute: typeof AppRelatedBlogChar126componentsContentArticleCardRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_public/rewards/~components/sections/rewards-list': {
      id: '/_app/_public/rewards/~components/sections/rewards-list'
      path: '/rewards/~components/sections/rewards-list'
      fullPath: '/rewards/~components/sections/rewards-list'
      preLoaderRoute: typeof AppPublicRewardsChar126componentsSectionsRewardsListRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_public/rewards/~components/sections/pictures-carousel': {
      id: '/_app/_public/rewards/~components/sections/pictures-carousel'
      path: '/rewards/~components/sections/pictures-carousel'
      fullPath: '/rewards/~components/sections/pictures-carousel'
      preLoaderRoute: typeof AppPublicRewardsChar126componentsSectionsPicturesCarouselRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_public/rewards/~components/sections/intro': {
      id: '/_app/_public/rewards/~components/sections/intro'
      path: '/rewards/~components/sections/intro'
      fullPath: '/rewards/~components/sections/intro'
      preLoaderRoute: typeof AppPublicRewardsChar126componentsSectionsIntroRouteImport
      parentRoute: typeof AppPublicLayoutRoute
    }
    '/_app/_related/blog/_article-content/$articleId/~components/article-with-error': {
      id: '/_app/_related/blog/_article-content/$articleId/~components/article-with-error'
      path: '/$articleId/~components/article-with-error'
      fullPath: '/blog/$articleId/~components/article-with-error'
      preLoaderRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_related/blog/_article-content/$articleId/~components/article-skeleton': {
      id: '/_app/_related/blog/_article-content/$articleId/~components/article-skeleton'
      path: '/$articleId/~components/article-skeleton'
      fullPath: '/blog/$articleId/~components/article-skeleton'
      preLoaderRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_related/blog/_article-content/$articleId/~components/article-sharing': {
      id: '/_app/_related/blog/_article-content/$articleId/~components/article-sharing'
      path: '/$articleId/~components/article-sharing'
      fullPath: '/blog/$articleId/~components/article-sharing'
      preLoaderRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_related/blog/_article-content/$articleId/~components/article-not-found': {
      id: '/_app/_related/blog/_article-content/$articleId/~components/article-not-found'
      path: '/$articleId/~components/article-not-found'
      fullPath: '/blog/$articleId/~components/article-not-found'
      preLoaderRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_related/blog/_article-content/$articleId/~components/dynamic-zone/related-articles': {
      id: '/_app/_related/blog/_article-content/$articleId/~components/dynamic-zone/related-articles'
      path: '/$articleId/~components/dynamic-zone/related-articles'
      fullPath: '/blog/$articleId/~components/dynamic-zone/related-articles'
      preLoaderRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_related/blog/_article-content/$articleId/~components/dynamic-zone/related-article-card': {
      id: '/_app/_related/blog/_article-content/$articleId/~components/dynamic-zone/related-article-card'
      path: '/$articleId/~components/dynamic-zone/related-article-card'
      fullPath: '/blog/$articleId/~components/dynamic-zone/related-article-card'
      preLoaderRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
    '/_app/_related/blog/_article-content/$articleId/~components/content-renderer/rich-content-renderer': {
      id: '/_app/_related/blog/_article-content/$articleId/~components/content-renderer/rich-content-renderer'
      path: '/$articleId/~components/content-renderer/rich-content-renderer'
      fullPath: '/blog/$articleId/~components/content-renderer/rich-content-renderer'
      preLoaderRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRouteImport
      parentRoute: typeof AppRelatedBlogLayoutRoute
    }
  }
}

interface AppAdminLayoutRouteChildren {
  AppAdminDashboardIndexRoute: typeof AppAdminDashboardIndexRoute
}

const AppAdminLayoutRouteChildren: AppAdminLayoutRouteChildren = {
  AppAdminDashboardIndexRoute: AppAdminDashboardIndexRoute,
}

const AppAdminLayoutRouteWithChildren = AppAdminLayoutRoute._addFileChildren(
  AppAdminLayoutRouteChildren,
)

interface AppPublicLayoutRouteChildren {
  AppPublicIndexRoute: typeof AppPublicIndexRoute
  AppPublicRewardsIndexRoute: typeof AppPublicRewardsIndexRoute
  AppPublicChar126componentsSectionsBenefitsRoute: typeof AppPublicChar126componentsSectionsBenefitsRoute
  AppPublicChar126componentsSectionsCompaniesMarqueeRoute: typeof AppPublicChar126componentsSectionsCompaniesMarqueeRoute
  AppPublicChar126componentsSectionsIntroRoute: typeof AppPublicChar126componentsSectionsIntroRoute
  AppPublicChar126componentsSectionsRecentArticlesRoute: typeof AppPublicChar126componentsSectionsRecentArticlesRoute
  AppPublicChar126componentsSectionsResourcesRoute: typeof AppPublicChar126componentsSectionsResourcesRoute
  AppPublicChar126componentsSectionsRewardsRoute: typeof AppPublicChar126componentsSectionsRewardsRoute
  AppPublicChar126componentsSectionsTaxesRoute: typeof AppPublicChar126componentsSectionsTaxesRoute
  AppPublicRewardsChar126componentsSectionsIntroRoute: typeof AppPublicRewardsChar126componentsSectionsIntroRoute
  AppPublicRewardsChar126componentsSectionsPicturesCarouselRoute: typeof AppPublicRewardsChar126componentsSectionsPicturesCarouselRoute
  AppPublicRewardsChar126componentsSectionsRewardsListRoute: typeof AppPublicRewardsChar126componentsSectionsRewardsListRoute
}

const AppPublicLayoutRouteChildren: AppPublicLayoutRouteChildren = {
  AppPublicIndexRoute: AppPublicIndexRoute,
  AppPublicRewardsIndexRoute: AppPublicRewardsIndexRoute,
  AppPublicChar126componentsSectionsBenefitsRoute:
    AppPublicChar126componentsSectionsBenefitsRoute,
  AppPublicChar126componentsSectionsCompaniesMarqueeRoute:
    AppPublicChar126componentsSectionsCompaniesMarqueeRoute,
  AppPublicChar126componentsSectionsIntroRoute:
    AppPublicChar126componentsSectionsIntroRoute,
  AppPublicChar126componentsSectionsRecentArticlesRoute:
    AppPublicChar126componentsSectionsRecentArticlesRoute,
  AppPublicChar126componentsSectionsResourcesRoute:
    AppPublicChar126componentsSectionsResourcesRoute,
  AppPublicChar126componentsSectionsRewardsRoute:
    AppPublicChar126componentsSectionsRewardsRoute,
  AppPublicChar126componentsSectionsTaxesRoute:
    AppPublicChar126componentsSectionsTaxesRoute,
  AppPublicRewardsChar126componentsSectionsIntroRoute:
    AppPublicRewardsChar126componentsSectionsIntroRoute,
  AppPublicRewardsChar126componentsSectionsPicturesCarouselRoute:
    AppPublicRewardsChar126componentsSectionsPicturesCarouselRoute,
  AppPublicRewardsChar126componentsSectionsRewardsListRoute:
    AppPublicRewardsChar126componentsSectionsRewardsListRoute,
}

const AppPublicLayoutRouteWithChildren = AppPublicLayoutRoute._addFileChildren(
  AppPublicLayoutRouteChildren,
)

interface AppRelatedComplianceLayoutRouteChildren {
  AppRelatedComplianceComplaintsRoute: typeof AppRelatedComplianceComplaintsRoute
  AppRelatedComplianceContactRoute: typeof AppRelatedComplianceContactRoute
  AppRelatedCompliancePrivacyPolicyRoute: typeof AppRelatedCompliancePrivacyPolicyRoute
  AppRelatedComplianceProhibitedProductsRoute: typeof AppRelatedComplianceProhibitedProductsRoute
  AppRelatedComplianceTermsOfUseRoute: typeof AppRelatedComplianceTermsOfUseRoute
}

const AppRelatedComplianceLayoutRouteChildren: AppRelatedComplianceLayoutRouteChildren =
  {
    AppRelatedComplianceComplaintsRoute: AppRelatedComplianceComplaintsRoute,
    AppRelatedComplianceContactRoute: AppRelatedComplianceContactRoute,
    AppRelatedCompliancePrivacyPolicyRoute:
      AppRelatedCompliancePrivacyPolicyRoute,
    AppRelatedComplianceProhibitedProductsRoute:
      AppRelatedComplianceProhibitedProductsRoute,
    AppRelatedComplianceTermsOfUseRoute: AppRelatedComplianceTermsOfUseRoute,
  }

const AppRelatedComplianceLayoutRouteWithChildren =
  AppRelatedComplianceLayoutRoute._addFileChildren(
    AppRelatedComplianceLayoutRouteChildren,
  )

interface AppRelatedBlogLayoutRouteChildren {
  AppRelatedBlogIndexRoute: typeof AppRelatedBlogIndexRoute
  AppRelatedBlogChar126componentsBlogArticlesRoute: typeof AppRelatedBlogChar126componentsBlogArticlesRoute
  AppRelatedBlogChar126componentsNavbarRoute: typeof AppRelatedBlogChar126componentsNavbarRoute
  AppRelatedBlogChar126componentsContentArticleCardRoute: typeof AppRelatedBlogChar126componentsContentArticleCardRoute
  AppRelatedBlogChar126componentsContentArticlesFiltersRoute: typeof AppRelatedBlogChar126componentsContentArticlesFiltersRoute
  AppRelatedBlogArticleContentArticleIdIndexRoute: typeof AppRelatedBlogArticleContentArticleIdIndexRoute
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRoute
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRoute
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRoute
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRoute
  AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRoute
  AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRoute
  AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRoute: typeof AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRoute
}

const AppRelatedBlogLayoutRouteChildren: AppRelatedBlogLayoutRouteChildren = {
  AppRelatedBlogIndexRoute: AppRelatedBlogIndexRoute,
  AppRelatedBlogChar126componentsBlogArticlesRoute:
    AppRelatedBlogChar126componentsBlogArticlesRoute,
  AppRelatedBlogChar126componentsNavbarRoute:
    AppRelatedBlogChar126componentsNavbarRoute,
  AppRelatedBlogChar126componentsContentArticleCardRoute:
    AppRelatedBlogChar126componentsContentArticleCardRoute,
  AppRelatedBlogChar126componentsContentArticlesFiltersRoute:
    AppRelatedBlogChar126componentsContentArticlesFiltersRoute,
  AppRelatedBlogArticleContentArticleIdIndexRoute:
    AppRelatedBlogArticleContentArticleIdIndexRoute,
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRoute:
    AppRelatedBlogArticleContentArticleIdChar126componentsArticleNotFoundRoute,
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRoute:
    AppRelatedBlogArticleContentArticleIdChar126componentsArticleSharingRoute,
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRoute:
    AppRelatedBlogArticleContentArticleIdChar126componentsArticleSkeletonRoute,
  AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRoute:
    AppRelatedBlogArticleContentArticleIdChar126componentsArticleWithErrorRoute,
  AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRoute:
    AppRelatedBlogArticleContentArticleIdChar126componentsContentRendererRichContentRendererRoute,
  AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRoute:
    AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticleCardRoute,
  AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRoute:
    AppRelatedBlogArticleContentArticleIdChar126componentsDynamicZoneRelatedArticlesRoute,
}

const AppRelatedBlogLayoutRouteWithChildren =
  AppRelatedBlogLayoutRoute._addFileChildren(AppRelatedBlogLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppAdminLayoutRoute: AppAdminLayoutRouteWithChildren,
  AppPublicLayoutRoute: AppPublicLayoutRouteWithChildren,
  AppRelatedComplianceLayoutRoute: AppRelatedComplianceLayoutRouteWithChildren,
  AppRelatedBlogLayoutRoute: AppRelatedBlogLayoutRouteWithChildren,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
  AuthSignInChar126componentsSignInFormRoute:
    AuthSignInChar126componentsSignInFormRoute,
  AuthSignUpChar126componentsSignUpFormRoute:
    AuthSignUpChar126componentsSignUpFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
